### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yunu599** [platipus9999/Tiktok-Bot#8]
it show this:Traceback (most recent call last):
  File "C:\Users\antje\Downloads\Tiktok-Bot-main\main.py", line 299, in <module>
    Zefoy().main()
  File "C:\Users\antje\Downloads\Tiktok-Bot-main\main.py", line 273, in main
    self.load_zefoy()
  File "C:\Users\antje\Downloads\Tiktok-Bot-main\main.py", line 130, in load_zefoy
    self.driver = self.setup_driver()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antje\Downloads\Tiktok-Bot-main\main.py", line 101, in setup_driver
    return Chrome(ChromeOptions().add_argument('--lang=es'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49381
from session not created: This version of ChromeDriver only supports Chrome version 118
Current browser version is 117.0.5938.134
Stacktrace:
        GetHandleVerifier [0x00AF4DE3+43907]
        (No symbol) [0x00A80741]
        (No symbol) [0x009733ED]
        (No symbol) [0x0099BE61]
        (No symbol) [0x0099B5B4]
        (No symbol) [0x0099528C]
        (No symbol) [0x009950BF]
        (No symbol) [0x009C9396]
        (No symbol) [0x009C8F2C]
        (No symbol) [0x009C2956]
        (No symbol) [0x0099E17E]
        (No symbol) [0x0099F32D]
        GetHandleVerifier [0x00DA5AF9+2865305]
        GetHandleVerifier [0x00DEE78B+3163435]
        GetHandleVerifier [0x00DE8441+3138017]
        GetHandleVerifier [0x00B7E0F0+605840]
        (No symbol) [0x00A8A64C]
        (No symbol) [0x00A86638]
        (No symbol) [0x00A8675F]
        (No symbol) [0x00A78DB7]
        BaseThreadInitThunk [0x765B00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77397BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77397B8E+238]

Exception ignored in: <function Chrome.__del__ at 0x000002B692450900>
Traceback (most recent call last):
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\antje\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Das Handle ist ungültig

**Comment by cometbh** [comment]
same
